
LOAD DATA LOCAL INFILE './load_files/drug_products_sub.txt' INTO TABLE Drug_Product FIELDS TERMINATED BY '\$' ENCLOSED BY '\"';

LOAD DATA LOCAL INFILE './load_files/drug_product_ingredients_sub.txt' INTO TABLE Drug_Product_Ingredients FIELDS TERMINATED BY '\$' ENCLOSED BY '\"';

LOAD DATA LOCAL INFILE './load_files/gender_lx_sub.txt' INTO TABLE Gender_LX FIELDS TERMINATED BY '\$' ENCLOSED BY '\"';

LOAD DATA LOCAL INFILE './load_files/outcome_lx_sub.txt' INTO TABLE Outcome_LX FIELDS TERMINATED BY '\$' ENCLOSED BY '\"';

LOAD DATA LOCAL INFILE './load_files/reactions_sub.txt' INTO TABLE Reactions FIELDS TERMINATED BY '\$' ENCLOSED BY '\"';

LOAD DATA LOCAL INFILE './load_files/report_drug_sub.txt' INTO TABLE Report_Drug FIELDS TERMINATED BY '\$' ENCLOSED BY '\"';

LOAD DATA LOCAL INFILE './load_files/report_drug_indication_sub.txt' INTO TABLE Report_Drug_Indication FIELDS TERMINATED BY '\$' ENCLOSED BY '\"';

LOAD DATA LOCAL INFILE './load_files/report_links_sub.txt' INTO TABLE Report_Links_LX FIELDS TERMINATED BY '\$' ENCLOSED BY '\"';

LOAD DATA LOCAL INFILE './load_files/report_type_lx_sub.txt' INTO TABLE Report_Type_LX FIELDS TERMINATED BY '\$' ENCLOSED BY '\"';

LOAD DATA LOCAL INFILE './load_files/reports_sub.txt' INTO TABLE Reports FIELDS TERMINATED BY '\$' ENCLOSED BY '\"'
	(REPORT_ID, REPORT_NO, VERSION_NO, @DATRECEIVED, @DATINTRECEIVED, MAH_NO, REPORT_TYPE_CODE, REPORT_TYPE_ENG,
	GENDER_CODE, GENDER_ENG, AGE, AGE_Y, AGE_UNIT_ENG, OUTCOME_CODE, OUTCOME_ENG, WEIGHT, WEIGHT_UNIT_ENG, HEIGHT,
	HEIGHT_UNIT_ENG, SERIOUSNESS_CODE, SERIOUSNESS_ENG, DEATH, DISABILITY, CONGENITAL_ANOMAY, LIFE_THREATENING,
	HOSP_REQUIRED, OTHER_MEDICALLY_IMP_COND, REPORTER_TYPE_ENG, SOURCE_CODE, SOURCE_ENG)
	SET DATRECEIVED = STR_TO_DATE(@DATRECEIVED, '%d-%b-%y'), DATINTRECEIVED = STR_TO_DATE(@DATINTRECEIVED, '%d-%b-%y');

LOAD DATA LOCAL INFILE './load_files/seriousness_lx_sub.txt' INTO TABLE Seriousness_LX FIELDS TERMINATED BY '\$' ENCLOSED BY '\"';

LOAD DATA LOCAL INFILE './load_files/source_lx_sub.txt' INTO TABLE Source_LX FIELDS TERMINATED BY '\$' ENCLOSED BY '\"';
